### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by kraftman** [Hackafe/atom-sync-settings#106]
Steps to reproduce
Install atom 
Install sync settings
Add personal Access Token
Add gist ID
Got to Packages -> Synchronise Settings -> backup.

Other steps tried: 
Tried using an access token with all permissions allowed, got same error
Tried making the gist public, same error
Tried pasting gist id as gist:841becc47c0e879d52d4 rather than 841becc47c0e879d52d4, same error.

I've probably done something wrong, let me know if there's any other information you need.

**Atom Version**: 1.0.2
**System**: Linux Mint
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.5.0

### Stack Trace

Uncaught SyntaxError: Unexpected token <

```
At file:///usr/share/atom/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.2%22%2C%22shellLoadTime%22%3A561%2C%22initialPaths%22%3A%5B%22atom%3A%2F%2Fconfig%22%5D%7D:1

SyntaxError: Unexpected token <
  at Object.parse (native)
  at /home/chris/.atom/packages/sync-settings/lib/sync-settings.coffee:99:24
  at Object.proto.sendError (/home/chris/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:32:13)
  at /home/chris/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:180:29
  at callCallback (/home/chris/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/home/chris/.atom/packages/sync-settings/node_modules/github/index.js:793:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -5:42.1.0 core:paste (atom-text-editor.editor.is-focused)
  2x -5:39.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:20.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:15.7.0 core:paste (atom-text-editor#sync-settings.personalAccessToken.editor.mini.is-focused)
     -0:03.3.0 sync-settings:backup (atom-text-editor#sync-settings.gistId.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "personalAccessToken": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
    "gistId": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.5.0

# Dev
No dev packages
```

**Comment by groupsky** [comment]
@kraftman are you behind a proxy? also I see the token and gistId are all nulls, is this because you obfuscated them, or this is actual value from the config?

**Comment by kraftman** [comment]
No problem. No proxy, and I've now tried from both work and home.
I removed the token and gist id but the nulls were there already so I left them in in case they were relevant, but maybe they are just being made by the bug reporting software.

Thanks

**Comment by kraftman** [comment]
Turns out the nulls were the problem, not sure what was copying it badly, either chrome or teamviewer, but after pasting the token/gist id into atom itself, then copying and pasting into the settings from there, it worked ok.

**Comment by jerone** [comment]
Great that you found out the problem.

**Comment by jameswlane** [comment]
I am behind a proxy, is there a work-around for being behind a proxy?
