### ISSUE TITLE
Uncaught SyntaxError: Unexpected token c

### ISSUE THREAD

**Issue by zhaopengme** [Hackafe/atom-sync-settings#113]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.5.0

### Stack Trace

Uncaught SyntaxError: Unexpected token c

```
At file:///C:/Users/Administrator/AppData/Local/atom/app-1.0.3/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CAdministrator%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.3%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CAdministrator%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.3%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.3%22%2C%22shellLoadTime%22%3A449%2C%22initialPaths%22%3A%5B%5D%7D:1

SyntaxError: Unexpected token c
  at Object.parse (native)
  at C:\Users\Administrator\.atom\packages\sync-settings\lib\sync-settings.coffee:117:24
  at Object.proto.sendError (C:\Users\Administrator\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\index.js:32:13)
  at C:\Users\Administrator\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:315:29
  at callCallback (C:\Users\Administrator\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at ClientRequest.<anonymous> (C:\Users\Administrator\.atom\packages\sync-settings\node_modules\github\index.js:809:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -5:27.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:54.6.0 core:paste (atom-text-editor#sync-settings.personalAccessToken.editor.mini.is-focused)
     -0:46.9.0 core:backspace (atom-text-editor#sync-settings.gistId.editor.mini.is-focused)
     -0:24.2.0 sync-settings:restore (atom-text-editor.editor.is-focused)
```

### Installed Packages

```coffee
# User
sync-settings, v0.5.0

# Dev
No dev packages
```

**Comment by steffenagger** [comment]
+1

**Comment by armink** [comment]
+1

**Comment by jerone** [comment]
Duplicate https://github.com/Hackafe/atom-sync-settings/issues/51

**Comment by zchwyng** [comment]
+1 also behind a proxy
