### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by ummahusla** [Hackafe/atom-sync-settings#117]
Hi, 
I've just installed Atom and I intended to download and install sync-setting package, but then I've got an error. 

/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56:21)
  at ErrorView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new ErrorView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:14:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:179:44
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:359:17
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:384:20
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents

Here is the screenshot: http://prntscr.com/82x8a1

Does this error related as a package error or there is a problem on my side? I've just downloaded Atom and to be honest I'm not sure where is problem comes from.

**Comment by ummahusla** [comment]
Well, I've managed to find out what was the issue, and it wasn't connected with that package. 

I had Atom version 1.0.2, I've upgraded it to 1.0.5 and hopefully, now Sync Settings are working fine for me.
