### ISSUE TITLE
Uncaught SyntaxError: Unexpected token c

### ISSUE THREAD

**Issue by DSigmund** [Hackafe/atom-sync-settings#118]
[Enter steps to reproduce below:]

1. Configured
2. First Backup

**Atom Version**: 1.0.0
**System**: FH-ATSP257
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught SyntaxError: Unexpected token c

```
At file:///C:/Users/sigmundd/AppData/Local/atom/app-1.0.0/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5Csigmundd%5C%5CMy%20Code%5C%5CGit01%5C%5Cawas%22%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Csigmundd%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.0%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Csigmundd%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.0%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22shellLoadTime%22%3A214%2C%22initialPaths%22%3A%5B%22C%3A%5C%5CUsers%5C%5Csigmundd%5C%5CMy%20Code%5C%5CGit01%5C%5Cawas%22%5D%7D:1

SyntaxError: Unexpected token c
  at Object.parse (native)
  at C:\Users\sigmundd\.atom\packages\sync-settings\lib\sync-settings.coffee:134:24
  at Object.proto.sendError (C:\Users\sigmundd\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\index.js:32:13)
  at C:\Users\sigmundd\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:180:29
  at callCallback (C:\Users\sigmundd\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at ClientRequest.<anonymous> (C:\Users\sigmundd\.atom\packages\sync-settings\node_modules\github\index.js:809:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -7:43.2.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -1:50.9.0 core:paste (atom-text-editor#sync-settings.personalAccessToken.editor.mini.is-focused)
     -0:42.8.0 command-palette:toggle (div.settings-view.pane-item)
     -0:40 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:40 sync-settings:backup (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "projectHome": "\"C:\\Users\\sigmundd\\My Code\\Git01\""
  },
  "sync-settings": {
    "_analyticsUserId": "cd6934e4-e4e4-4562-b25d-4ebda0da91c6",
    "personalAccessToken": "######################",
    "gistId": "################"
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autoclose-html, v0.18.0
color-picker, v2.0.7
docblockr, v0.7.2
file-icons, v1.5.8
highlight-selected, v0.10.1
line-ending-converter, v1.2.0
linter, v1.3.1
linter-htmlhint, v0.0.17
linter-jshint, v1.1.4
linter-stylelint, v0.3.3
minimap, v4.10.1
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
pigments, v0.8.1
remote-sync, v3.1.2
Stylus, v1.0.0
sync-settings, v0.6.0
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by safferli** [comment]
I have the same issue: 

[Enter steps to reproduce below:]

1. Install sync-settings
2. run sync-settings:Backup command
3. wait a bit, then error pops up; note that I am behind a proxy, if this is of an issue

**Atom Version**: 1.0.10
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0


### Stack Trace

Uncaught SyntaxError: Unexpected token c

```
At file:///C:/Users/christoph.safferling/AppData/Local/atom/app-1.0.10/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22atom%3A%2F%2Fconfig%22%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Cchristoph.safferling%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.10%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Cchristoph.safferling%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.10%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.10%22%2C%22shellLoadTime%22%3A287%2C%22initialPaths%22%3A%5B%22atom%3A%2F%2Fconfig%22%5D%7D:1

SyntaxError: Unexpected token c
  at Object.parse (native)
  at C:\Users\christoph.safferling\.atom\packages\sync-settings\lib\sync-settings.coffee:134:24
  at Object.proto.sendError (C:\Users\christoph.safferling\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\index.js:32:13)
  at C:\Users\christoph.safferling\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:180:29
  at callCallback (C:\Users\christoph.safferling\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at ClientRequest.<anonymous> (C:\Users\christoph.safferling\.atom\packages\sync-settings\node_modules\github\index.js:809:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -2:55.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:53.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:52.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:52.6.0 sync-settings:view-backup (div.settings-view.pane-item)
     -2:35.6.0 core:move-up (div.settings-view.pane-item)
     -2:34.2.0 command-palette:toggle (div.settings-view.pane-item)
     -2:32.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:30.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:30 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:29.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:29.3.0 sync-settings:backup (div.settings-view.pane-item)
     -0:32.4.0 command-palette:toggle (a.btn-issue.btn.btn-error)
     -0:29.7.0 sync-settings:backup (a.btn-issue.btn.btn-error)
     -0:07.4.0 command-palette:toggle (div.settings-view.pane-item)
     -0:05.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false
  },
  "sync-settings": {
    "_analyticsUserId": "2b724002-696e-4a96-b899-8aa080b0c3e0",
    "analytics": false,
    "personalAccessToken": "yaddayaddayadda",
    "gistId": "yarrr"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
file-icons, v1.6.9
foldingtext-for-atom, v0.9.0
highlight-line, v0.11.0
language-latex, v0.6.1
minimap, v4.13.2
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by kutyel** [comment]
Happened the same to me, I suspect **the corporate proxy** might be causing this...

[Enter steps to reproduce below:]

1. Config Sync Settings
2. Ctrl+Alt+P
3. Sync Settings: Backup

**Atom Version**: 1.0.11
**System**: Unknown Windows Version
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0


### Stack Trace

Uncaught SyntaxError: Unexpected token c

```
At file:///C:/Users/fcr/AppData/Local/atom/app-1.0.11/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22X%3A%5C%5CGestaViews%22%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Cfcr%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.11%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Cfcr%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.11%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.11%22%2C%22shellLoadTime%22%3A312%2C%22initialPaths%22%3A%5B%22X%3A%5C%5CGestaViews%22%5D%7D:1

SyntaxError: Unexpected token c
    at Object.parse (native)
    at C:\Users\fcr\.atom\packages\sync-settings\lib\sync-settings.coffee:134:24
    at Object.proto.sendError (C:\Users\fcr\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\index.js:32:13)
    at C:\Users\fcr\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:180:29
    at callCallback (C:\Users\fcr\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
    at ClientRequest.<anonymous> (C:\Users\fcr\.atom\packages\sync-settings\node_modules\github\index.js:809:17)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:166:7)
    at TLSSocket.socketErrorListener (_http_client.js:254:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:166:7)
    at net.js:438:14
    at process._tickCallback (node.js:357:13)
```

### Commands

```
     -3:16.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
 13x -3:11.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -2:56.1.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -2:55.5.0 core:copy (atom-text-editor.editor.is-focused)
     -2:40.6.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -2:40.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:38.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:27.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:27.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:49.4.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:49.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:46.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:42.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.8.0 sync-settings:backup (atom-text-editor.editor)
     -0:02.7.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -0:02.5.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "46c25130-8859-4c0e-9fa6-739578df6aad",
    "personalAccessToken": "7d4a2134e9dd938602324c86c6136ed116fcad8f",
    "gistId": "c53fa191081a84b4653a",
    "checkForUpdatedBackup": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
code-links, v0.3.11
linter, v1.5.1
linter-jshint, v1.2.0
minimap, v4.13.3
monokai, v0.18.0
sync-settings, v0.6.0
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by jerone** [comment]
Duplicate https://github.com/Hackafe/atom-sync-settings/issues/51

**Comment by jkokkeler** [comment]
Suspect same problem, running proxy 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0


### Stack Trace

Uncaught SyntaxError: Unexpected token c

```
At file:///usr/share/atom/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fhome%2Fjoep%2F.atom%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.19%22%2C%22shellLoadTime%22%3A749%2C%22initialPaths%22%3A%5B%22%2Fhome%2Fjoep%2F.atom%22%5D%7D:1

SyntaxError: Unexpected token c
  at Object.parse (native)
  at /home/joep/.atom/packages/sync-settings/lib/sync-settings.coffee:158:24
  at Object.proto.sendError (/home/joep/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:32:13)
  at /home/joep/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:315:29
  at callCallback (/home/joep/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
  at ClientRequest.<anonymous> (/home/joep/.atom/packages/sync-settings/node_modules/github/index.js:809:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:169:7)
  at TLSSocket.socketErrorListener (_http_client.js:259:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at emitErrorNT (net.js:1233:8)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```

### Commands

```
     -2:22.7.0 command-palette:toggle (atom-text-editor#sync-settings.gistId.editor.mini.is-focused)
  3x -2:19.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:18.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:17.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:17.2.0 sync-settings:view-backup (atom-text-editor#sync-settings.gistId.editor.mini)
     -2:11.2.0 command-palette:toggle (div.settings-view.pane-item)
     -2:09.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:08.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:08.3.0 sync-settings:restore (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "c0aaebcb-190c-47e9-9366-bb771ec983d4",
    "gistId": "63c92bd6006db76a24b2",
    "personalAccessToken": "4b9143aa30954b4367a203f3af003c98591a2633"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.6.0

# Dev
No dev packages
```
