### ISSUE TITLE
Uncaught Error: Cannot find module 'q'

### ISSUE THREAD

**Issue by Evpok** [Hackafe/atom-sync-settings#128]
1. Try to install the package

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught Error: Cannot find module 'q'

```
At module.js:336

Error: Cannot find module 'q'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Loïc\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Loïc\.atom\packages\sync-settings\lib\package-manager.coffee:7:5)
  at Object.<anonymous> (C:\Users\Loïc\.atom\packages\sync-settings\lib\package-manager.coffee:4:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Loïc\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Immediate._onImmediate (C:\Users\Loïc\.atom\packages\sync-settings\lib\sync-settings.coffee:19:25)
  at processImmediate [as _immediateCallback] (timers.js:371:17)

```

### Commands

```
     -2:07.5.0 settings-view:open (atom-pane.pane.active)
     -2:01.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by jerone** [comment]
It looks like something when wrong installing the required modules for this package. Did you restart Atom? Or tried reinstalling this package?

**Comment by Komanaki** [comment]
Same here on Windows 10 x64 : have done a fresh install of Atom today (1.0.15), installed sync-settings (0.6.0), restarted Atom and get exactly that error.
No changes after uninstall / reinstall of the package.
Don't hesitate to ask me any other useful information you need to resolve this issue !

**Comment by jerone** [comment]
If you've got time, checkout this repo and install with a newer version of [q](https://www.npmjs.com/package/q) module.

**Comment by Komanaki** [comment]
Cloned the repo into my .packages directory, `npm install` into it and now Atom says it can't found the `underscore-plus`.
The npm log says it installed that module though :
```
underscore-plus@1.6.6 node_modules\underscore-plus
└── underscore@1.6.0
```
No chances when i set the version of `q`

**Comment by jerone** [comment]
Can you try running `apm install` to install all packages.

**Comment by Komanaki** [comment]
Ran `apm install` with still no changes, same `Cannot find module 'underscore-plus'` error.

**Comment by Evpok** [comment]
Same. It's actually a fresh install I did because several modules were
falling following the .13 update.

**Comment by Evpok** [comment]
Also I am not sure of how to access atom's underlying `node` to install a newer Q.

**Comment by Nonlimit** [comment]
Have the same problem :(

**Atom Version**: 1.0.18
**System**:  Windows 8.1
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0


### Stack Trace

Uncaught Error: Cannot find module 'q'

```
At module.js:336

Error: Cannot find module 'q'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Администратор\AppData\Local\atom\app-1.0.18\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Администратор\.atom\packages\sync-settings\lib\package-manager.coffee:7:5)
    at Object.<anonymous> (C:\Users\Администратор\.atom\packages\sync-settings\lib\package-manager.coffee:4:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Администратор\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "personalAccessToken": "8d861ed092c725709d4f13ae7d4b882b0201e181",
    "gistId": "a76628afdcba672fffce"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by Nonlimit** [comment]
uninstall Atom Version: 1.0.18 and install Atom version 1.0.10 and error has been gone

**Comment by Evpok** [comment]
Doesn't sound like a viable solution, but thanks. Anyway, this issue should probably be closed, as https://github.com/atom/atom/issues/8891 suggests that the issue lies upstream.

**Comment by dirk-thomas** [comment]
Is the problem still happening for newer versions of Atom for anyone?

**Comment by dirk-thomas** [comment]
Without further information this can not be debugged. Assuming this is not a problem anymore I will close this ticket. If you are still experiencing the problem please comment with more information.
