### ISSUE TITLE
Uncaught SyntaxError: Unexpected token g

### ISSUE THREAD

**Issue by clayreimann** [Hackafe/atom-sync-settings#152]
1. Sync from remote backup

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught SyntaxError: Unexpected token g

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fclay%2Fgithub%2Fgithub-js%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.2.4%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fclay%2Fgithub%2Fgithub-js%22%5D%7D:1

SyntaxError: Unexpected token g
    at Object.parse (native)
    at /Users/clay/.atom/packages/sync-settings/lib/sync-settings.coffee:240:28
    at Object.proto.sendError (/Users/clay/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:32:13)
    at /Users/clay/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:315:29
    at callCallback (/Users/clay/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
    at ClientRequest.<anonymous> (/Users/clay/.atom/packages/sync-settings/node_modules/github/index.js:809:17)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at connectErrorNT (net.js:993:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### Commands

```
     -0:53.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:52.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:51.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:48.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:47.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:47.9.0 sync-settings:restore (atom-text-editor.editor)
     -0:38.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:35.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:33.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.6.0 sync-settings:restore (atom-text-editor.editor)
     -0:31.3.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
  2x -0:30.7.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:29.2.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:28.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:22.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "sepia-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".idea",
      ".DS_Store",
      "test-output"
    ],
    "disabledPackages": [
      "webbox-color",
      "jshint",
      "atom-color-highlight",
      "git-plus",
      "linter-coffeelint",
      "autocomplete-atom-api",
      "language-sql",
      "git-history"
    ],
    "audioBeep": false,
    "packagesWithKeymapsDisabled": [
      "advanced-new-file"
    ]
  },
  "sync-settings": {
    "gistId": "3552f6d6c54c3bb00346",
    "personalAccessToken": "b74756d6f4e442bd49a1a965e639feab0faa7ecb",
    "_analyticsUserId": "e3772061-f607-4391-87e7-6275dcea3a64",
    "_lastBackupHash": "0405dfda8810cc969ae0c1610902a726a510cbc1"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-handlebars, v1.2.0
cucumber, v0.5.0
docblockr, v0.7.3
editorconfig, v1.2.2
file-icons, v1.6.13
git-diff-details, v0.21.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-bats, v0.1.0
language-jade, v0.6.2
language-nginx, v0.6.1
linter, v1.11.3
linter-eslint, v5.2.5
linter-jscs, v3.2.0
linter-jshint, v1.2.1
linter-jsxhint, v0.1.2
live-archive, v0.1.15
pigments, v0.19.1
react, v0.12.10
sepia-syntax, v1.0.5
set-syntax, v0.3.0
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
tool-bar, v0.1.9
wordcount, v2.4.1

# Dev
git-diff-details, v0.21.0
```

**Comment by clayreimann** [comment]
Possible dup of #151

**Comment by dirk-thomas** [comment]
I can't reproduce this. Can anybody? Is the same problem still happening for you? Have you tried using newer versions of Atom?

**Comment by clayreimann** [comment]
I haven't seen it recently. Will reopen if I do.

**Comment by dirk-thomas** [comment]
Also in the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by mildfuzz** [comment]
I just got this issue.

**Comment by mildfuzz** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2


### Stack Trace

Uncaught SyntaxError: Unexpected token g

```
At file:///opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2Fjohn%2Fworkspace%2Factive%2Forder-to-go%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fjohn%2Fworkspace%2Factive%2Forder-to-go%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2Fopt%2Fhomebrew-cask%2FCaskroom%2Fatom%2F1.4.1%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2Fopt%2Fhomebrew-cask%2FCaskroom%2Fatom%2F1.4.1%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22COLORFGBG%22%3A%227%3B0%22%2C%22TERM_PROGRAM%22%3A%22iTerm.app%22%2C%22LSCOLORS%22%3A%22Gxfxcxdxbxegedabagacad%22%2C%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F7_%2Fhk_xgfm96c7bp75j3652d3880000gn%2FT%2F%22%2C%22ITERM_SESSION_ID%22%3A%22w0t1p0%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0x0%3A0x0%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22LESS%22%3A%22-R%22%2C%22HOME%22%3A%22%2FUsers%2Fjohn%22%2C%22_%22%3A%22%2Fusr%2Fbin%2Fopen%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.o8qwE2yMTb%2FListeners%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.X3Gz7UlEIz%2FRender%22%2C%22ZSH%22%3A%22%2FUsers%2Fjohn%2F.oh-my-zsh%22%2C%22PAGER%22%3A%22less%22%2C%22SHLVL%22%3A%222%22%2C%22LC_CTYPE%22%3A%22en_GB.UTF-8%22%2C%22PATH%22%3A%22%2Fusr%2Flocal%2Fsbin%3A%2Fusr%2Flocal%2Fsbin%3A%2Fusr%2Flocal%2Fbin%3A%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22TERM%22%3A%22xterm%22%2C%22LOGNAME%22%3A%22john%22%2C%22XPC_SERVICE_NAME%22%3A%22com.github.atom.68512.194F54F7-479D-49F4-914A-ABB1F1F7CC1B%22%2C%22LANG%22%3A%22en_GB.UTF-8%22%2C%22ITERM_PROFILE%22%3A%22Default%22%2C%22SECURITYSESSIONID%22%3A%22186a8%22%2C%22USER%22%3A%22john%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22PWD%22%3A%22%2FUsers%2Fjohn%2Fworkspace%2Factive%2Forder-to-go%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Fjohn%2F.atom%22%7D%2C%22appVersion%22%3A%221.7.2%22%2C%22atomHome%22%3A%22%2FUsers%2Fjohn%2F.atom%22%2C%22shellLoadTime%22%3A538%7D:1

SyntaxError: Unexpected token g
    at Object.parse (native)
    at /Users/john/.atom/packages/sync-settings/lib/sync-settings.coffee:178:24
    at [object Object].global.sendError (/Users/john/.atom/packages/sync-settings/node_modules/github4/index.js:729:13)
    at /Users/john/.atom/packages/sync-settings/node_modules/github4/index.js:736:29
    at callCallback (/Users/john/.atom/packages/sync-settings/node_modules/github4/index.js:613:17)
    at ClientRequest.<anonymous> (/Users/john/.atom/packages/sync-settings/node_modules/github4/index.js:684:17)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at connectErrorNT (net.js:996:8)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

### Commands

```
  2x -2:19.3.0 core:paste (atom-text-editor#sync-settings.personalAccessToken.editor.mini.is-focused)
     -0:48.8.0 core:close (div.package-detail.panels-item)
     -0:45.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:40.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:31.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.5.0 sync-settings:backup (atom-text-editor.editor)
     -0:02.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "67c5005a-aad8-4597-9402-a48a6812a990",
    "gistId": "f1cae25893b32fe81767ceeced33dafd",
    "personalAccessToken": "dd457e00d2c566200fb32f1865600fade46bcb47"
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0
highlight-selected, v0.11.2
linter, v1.11.4
linter-eslint, v7.2.1
open-recent, v5.0.0
pigments, v0.26.0
raml, v0.2.0
semicol, v1.1.1
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
@mildfuzz In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by rubencaro** [comment]
I have it too, just like @mildfuzz. @clayreimann please reopen this!

Atom 1.7.3
Fedora23
sync-settings 0.7.2

**Comment by anoff** [comment]
Same issue during restore, bump for reopen

atom 1.8.0
OSX 10.11.15
sync-settings 0.7.2

**Comment by dirk-thomas** [comment]
Assuming you have the same stacktrace (sync-settings.coffee:178) can you please post the error message from the console. The message might shed some light into why the problem is happening.
