### ISSUE TITLE
Cannot find module 'underscore-plus’ when in dev mode

### ISSUE THREAD

**Issue by danielbayley** [Hackafe/atom-sync-settings#181]
If I open a project/window in dev mode, this package throws a `Cannot find module 'underscore-plus’ when in dev mode` error.

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Failed to activate the sync-settings package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Dan/Library/Application Support/Atom/dev/packages/sync-settings/lib/sync-settings.coffee:4:5)
    at Object.<anonymous> (/Users/Dan/Library/Application Support/Atom/dev/packages/sync-settings/lib/sync-settings.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
     -2:33.2.0 sync-settings:backup (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:44.3.0 core:close (div.pane-item.native-key-bindings.about)
     -0:42.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:38.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.3.0 package-settings:sync-settings (atom-text-editor.editor)
     -0:26.8.0 core:close (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.js": [
        "ffx"
      ],
      "text.xml": [
        "als",
        "sdef"
      ],
      "text.xml.plist": [
        "plist"
      ]
    },
    "disabledPackages": [
      "autocomplete",
      "remember-session",
      "file-type-icons",
      "red-wavy-underline",
      "color-gutter",
      "word-count",
      "seti-icons",
      "livereload",
      "environment",
      "test-status",
      "tree-view-breadcrumb",
      "circle-ci",
      "travis-ci-status",
      "regex-railroad-diagram",
      "Zen",
      "metrics",
      "project-environment",
      "language-dots",
      "language-env",
      "plist-converter",
      "build",
      "pigments",
      "markdown-toc",
      "emmet",
      "keybinding-cheatsheet",
      "language-cjsx",
      "url-tidy",
      "multiple-keymaps",
      "preview",
      "synced-sidebar",
      "git-travel",
      "tree-view-git-branch",
      "tree-view-git-projects",
      "package-templates",
      "follow-finder-aliases",
      "new-tab",
      "linter-scss-lint",
      "atom-react-preview",
      "env-from-shell",
      "imdone-atom",
      "tablr",
      "postcss-sorting",
      "markdown-scroll-sync"
    ],
    "ignoredNames": [
      ".DS_Store",
      "._*",
      "Icon",
      ".git",
      "*.pyc",
      "*.rsrc"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "~/Library/Application Support/Atom/dev/packages",
    "themes": [
      "nucleus-dark-ui",
      "adventurous-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": " ",
    "_lastBackupHash": "e73f64dd8cc38cb26f4634c1d0ad00cb59e6bd67",
    "analytics": false,
    "extraFiles": [
      "projects.cson",
      "coffeelint.json",
      "linter.cson",
      "toolbar.cson"
    ],
    "gistId": "XXXXXXXXXXXXXXX",
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  }
}
```

### Installed Packages

```coffee
# User
adventurous-syntax, v0.2.0
api-docs, v0.0.4
atom-calca, v0.3.0
atom-html-preview, v0.1.13
atom-jasmine, v0.8.1
atom-smart-tabs, v0.1.0
atom-touch-events, v0.23.0
auto-detect-indentation, v0.4.2
auto-update-packages, v1.0.0
autoclose-html, v0.20.0
autocomplete-html-entities, v0.1.0
autocomplete-json, v1.5.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
autocomplete-swift, v1.0.1
autohide-tree-view, v0.25.1
bezier-curve-editor, v0.7.2
browser-plus, v0.0.54
build-npm-apm, v0.8.0
build-xcodebuild, v0.1.0
clipboard-plus, v0.5.1
coffee-porter, v0.8.1
color-picker, v2.1.1
contextual-preview, v0.0.0
copy-path, v0.3.1
cson, v2.0.1
css-snippets, v0.9.0
custom-title, v1.0.1
default-language, v0.3.0
disable-grammars, v0.1.1
disable-keybindings, v0.6.0
editorconfig, v1.2.4
external-open, v0.6.1
file-icons, v1.6.14
file-types, v0.5.1
flex-tool-bar, v0.7.3
flexbox-snippets, v0.3.0
html-id-class-snippets, v1.4.1
jQuery, v1.2.1
jade-snippets, v0.5.0
language-ansible, v0.1.3
language-apache, v1.4.0
language-gitignore, v0.2.0
language-haml, v0.23.15
language-jade, v0.6.3
language-postcss, v1.1.3
language-svg, v0.9.0
language-swift, v0.4.0
linter, v1.11.3
linter-ansible-lint, v0.0.7
linter-coffeelint, v1.1.2
linter-doiuse, v0.2.3
linter-htmlhint, v1.0.2
linter-jade, v0.3.2
linter-js-yaml, v1.2.5
linter-jshint, v1.3.0
linter-jsonlint, v1.1.5
linter-less, v2.4.0
linter-markdown, v1.4.2
linter-perl, v0.7.2
linter-rubocop, v0.4.7
linter-sass-lint, v1.0.5
linter-shellcheck, v1.1.0
linter-stylelint, v1.10.4
linter-swiftc, v2.0.0
linter-swiftlint, v1.1.0
linter-xmllint, v1.3.0
make-executable, v0.1.1
markdown-preview-plus, v2.2.2
markdown-table-formatter, v2.7.2
markdown-themeable-pdf, v0.10.2
modular-keymaps, v0.1.0
move-status-items, v0.0.11
navigate, v0.1.13
new-file-plus, v0.2.1
nucleus-dark-ui, v0.7.4
open-recent, v5.0.0
package-settings, v1.0.1
pain-split, v1.4.0
pdf-view, v0.39.0
project-manager, v2.7.6
react, v0.14.1
react-snippets, v0.3.0
rest-client, v0.5.0
sequential-command, v0.3.0
simple-drag-drop-text, v0.3.0
source-preview-jade, v0.1.1
source-preview-react, v0.2.0
svg-preview, v0.7.3
sync-settings, v0.6.0
tab-control, v0.6.9
tabs-to-spaces, v1.0.1
takana-atom, v0.1.0
terminal-panel, v1.14.1
text-manipulation, v0.6.0
tool-bar, v0.2.0
tree-view-git-status, v0.2.2
url-tidy, v0.1.1
wordcount, v2.6.0

# Dev
alt-spinner, vundefined
browser-plus, v0.0.45
color-picker, v2.0.13
contextual-preview, v0.0.0
disable-menus, v0.0.0
modular-keymaps, v0.1.0
nucleus-dark-ui, v0.6.5
sync-settings, v0.6.0
terminal-panel, v1.14.1
test-package, v0.0.0
text-manipulation, v0.6.0
```

**Comment by dirk-thomas** [comment]
After cloning this package into your dev/packages folder have you installed its dependencies using `npm install`?

Also in the above error report you have shared you `personalAccessToken`. You might want to revoke it to prevent abuse.

**Comment by danielbayley** [comment]
> After cloning this package into your dev/packages folder have you installed its dependencies using npm install?

I didn’t realise I’d forked it; that was it, thanks.

> Also in the above error report you have shared you personalAccessToken. You might want to revoke it to prevent abuse.

Yikes, the ‘copy’ function in the notification ought to exclude such information! Thanks again.
