### ISSUE TITLE
Can't install this plugin

### ISSUE THREAD

**Issue by Mrzzchao** [Hackafe/atom-sync-settings#186]
Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Mr_chao/.atom/packages/atom-sync-settings-master/lib/sync-settings.coffee:4:5)
    at Object.<anonymous> (file:///C:/Users/Mr_chao/.atom/packages/atom-sync-settings-master/lib/sync-settings.coffee:2:1)
    at Module._compile (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:720:27)
    at C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:116:28
    at Package.module.exports.Package.measure (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:684:21)
    at module.exports (C:\Users\Mr_chao\AppData\Local\atom\app-1.5.3\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Mr_chao/AppData/Local/atom/app-1.5.3/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/Mr_chao/AppData/Local/atom/app-1.5.3/resources/app.asar/static/index.js:41:9)

**Comment by dirk-thomas** [comment]
Can you please mention which version of Atom as well as this package you are using. Also are you using the developer mode?

**Comment by Mrzzchao** [comment]
Thanks for your attention,and my question has been solved.The reason is possibly that I don't install the 'underscore-plus'.Thank you!

**Comment by dirk-thomas** [comment]
I the issue is resolved for you please close the ticket.
