### ISSUE TITLE
Uncaught Error: Cannot find module 'loophole'

### ISSUE THREAD

**Issue by crudo** [Hackafe/atom-sync-settings#189]
1. Open Atom

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught Error: Cannot find module 'loophole'

```
At module.js:338

Error: Cannot find module 'loophole'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/crudo/.atom/packages/sync-settings/lib/tracker.coffee:6:21)
    at Object.<anonymous> (/Users/crudo/.atom/packages/sync-settings/lib/tracker.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Immediate._onImmediate (/Users/crudo/.atom/packages/sync-settings/lib/sync-settings.coffee:20:18)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "blackboard-theme-original"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "c2d9ac39-58dc-4f14-ae5a-d063eaa7f6c8",
    "_lastBackupHash": "74317aee1fba17fb2090557267b1629847b53f6c",
    "gistId": "90cbf71690db657ce8a7",
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
blackboard-theme-original, v0.3.2
dash, vundefined
emmet, v2.4.2
file-icons, v1.6.17
language-diff, v0.4.0
linter, v1.11.3
linter-eslint, v7.0.0
project-manager, v2.7.6
react, v0.14.1
react-snippets, v0.3.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by dirk-thomas** [comment]
'loophole' is  a declared dependency of this package: https://github.com/Hackafe/atom-sync-settings/blob/394cc0008724b4e6541c7e826fafb445ae0f57ca/package.json#L24

Therefore I assume you haven't installed the released package through the UI but use a manually cloned version of the repo. Have you installed all dependencies with `npm install`?

**Comment by crudo** [comment]
I have no idea how I install it, but uninstall through apm and install it again helped. Thanks anyway!
