### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/masaya/.atom/packages/sync-settin...

### ISSUE THREAD

**Issue by ore-public** [Hackafe/atom-sync-settings#196]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/masaya/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/masaya/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/masaya/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/masaya/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/masaya/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/masaya/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/masaya/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
  4x -2:11.2.0 core:move-down (atom-text-editor.editor.query-input.is-focused)
  2x -2:10.5.0 core:move-up (atom-text-editor.editor.query-input.is-focused)
  4x -2:10.2.0 core:move-down (atom-text-editor.editor.query-input.is-focused)
  4x -2:05.7.0 blur (atom-text-editor.editor.query-input.is-focused)
  2x -2:01.2.0 core:move-down (atom-text-editor.editor.query-input.is-focused)
  2x -2:00.8.0 core:move-up (atom-text-editor.editor.query-input.is-focused)
  4x -2:00.3.0 core:move-down (atom-text-editor.editor.query-input.is-focused)
  2x -1:51.4.0 blur (atom-text-editor.editor.query-input.is-focused)
     -1:38 core:move-up (atom-text-editor.editor.query-input.is-focused)
  5x -1:37.8.0 core:move-down (atom-text-editor.editor.query-input.is-focused)
  3x -1:31.3.0 blur (atom-text-editor.editor.query-input.is-focused)
     -1:31.2.0 data-atom:toggle-results-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -1:27.7.0 settings-view:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -1:27.6.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -1:27.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
 13x -1:27.6.0 blur (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  },
  "sync-settings": {
    "_analyticsUserId": "bfe907d6-8882-4126-b3b9-f34c763b9b11",
    "_lastBackupHash": "b6c427f4176e67fb69c83749146a28406a5b1e47",
    "gistId": "b89499fd642914a916f6",
    "personalAccessToken": "79e26d2e82dc7e8bc6ae373bf39fa1d2ac0cf2fd"
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.18
language-diff, v0.4.0
language-slim, v0.5.0
merge-conflicts, v1.3.7
pigments, v0.24.4
sync-settings, v0.7.0
synced-sidebar, v0.4.3
terminal-plus, v0.14.5
vim-mode-plus, v0.23.0
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by ore-public** [comment]
already reported

**Comment by dirk-thomas** [comment]
Duplicate of #194.

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.
