### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open /.atom/packages/sync-settings/...

### ISSUE THREAD

**Issue by bensk** [Hackafe/atom-sync-settings#197]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Ben/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/Ben/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/Ben/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/Ben/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/Ben/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/Ben/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/Ben/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:41.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-bensk-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "wordcount",
      "processing",
      "script"
    ],
    "themes": [
      "one-dark-ui",
      "bensk-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "55bc9c53-a738-4aaf-bc96-ccdb11b3046a",
    "_lastBackupHash": "b02636547f6dd841b64af74c4c08f1bd672b2924",
    "gistId": "6a6320f6aff87fc3cdec",
    "personalAccessToken": "956a820aa4f0e28b72d17b0c519449c770cd63dd"
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.16
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
bensk-syntax, v0.8.0
color-picker, v2.1.1
emmet, v2.4.2
html-entities, v0.4.0
language-arduino, v0.4.1
one-tab, v0.8.0
processing-language, v0.2.0
sync-settings, v0.7.0
typewriter, v0.3.5

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
Duplicate of #194
