### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/danielsmink/.atom/packages/sync-s...

### ISSUE THREAD

**Issue by danielsmink** [Hackafe/atom-sync-settings#202]
1. Updated the plugin in an open project

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/danielsmink/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/danielsmink/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/danielsmink/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/danielsmink/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/danielsmink/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/danielsmink/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/danielsmink/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
  2x -4:09.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:09.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -4:08.8.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -4:08.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:00.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:00.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:00.8.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -4:00.8.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -3:59 core:save (atom-text-editor.editor.is-focused)
     -3:42.4.0 core:copy (atom-text-editor.editor.is-focused)
     -3:37.4.0 core:paste (atom-text-editor.editor.is-focused)
     -3:32.6.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -3:32.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:16.1.0 core:delete (atom-text-editor.editor.is-focused)
     -2:15.2.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -2:14.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "8cc8d8fb-8e90-4d88-9f9b-9f16827bc957",
    "_lastBackupHash": "650a6325a91397dd7993db499bc728a310a43c3b",
    "gistId": "1ebdbb01654e142241f3",
    "personalAccessToken": "eac6c87681ea97f0f461f4bfddb7d25d240a6dcb"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.26
atom-typescript, v8.3.0
docblockr, v0.7.3
emmet, v2.4.2
language-docker, v1.1.6
linter, v1.11.3
linter-eslint, v7.0.0
linter-php, v1.2.0
pigments, v0.24.4
save-session, v0.16.0
seti-syntax, v0.4.1
seti-ui, v0.9.1
sync-settings, v0.7.0
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by jerone** [comment]
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.
