### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/anders/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by baelter** [Hackafe/atom-sync-settings#203]
[Enter steps to reproduce below:]

1. Open atom

**Atom Version**: 1.5.4
**System**: "Manjaro Linux"
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/anders/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/home/anders/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/home/anders/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/home/anders/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/home/anders/.atom/packages/sync-settings/lib/sync-settings.coffee:205:9)
    at Object.SyncSettings.checkForUpdate (/home/anders/.atom/packages/sync-settings/lib/sync-settings.coffee:18:3)
    at Immediate._onImmediate (/home/anders/.atom/packages/sync-settings/lib/sync-settings.coffee:35:9)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -2:00.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -2:00.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-jscs"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      "node_modules"
    ],
    "projectHome": "/home/anders/Projects"
  },
  "sync-settings": {
    "_analyticsUserId": "e7a851d0-e658-4fc5-9d35-21028b7f7b26",
    "_lastBackupHash": "cd76a57791f4fb7493a19f22abaad99de7b8dbf1",
    "analytics": false,
    "extraFiles": [
      "toolbar.json"
    ],
    "gistId": "e0c71cd1cb32e97b1d49",
    "personalAccessToken": "4152c2e7ed09cb0ae05a9a90178c3a930b70c421"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-ternjs, v0.13.2
autoclose-html, v0.23.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.0
autocomplete-sass, v0.1.0
color-picker, v2.1.1
compare-files, v0.6.2
css-snippets, v0.9.0
custom-title, v1.0.1
docblockr, v0.7.3
editorconfig, v1.2.4
external-open, v0.6.3
file-icons, v1.6.18
filesize, v0.4.2
flex-tool-bar, v0.8.1
git-log, v0.4.1
go-plus, v3.5.4
highlight-selected, v0.11.2
language-diff, v0.4.0
language-groovy, v0.5.0
language-nginx, v0.6.1
language-qml, v1.0.0
language-rspec, v0.5.0
language-svg, v0.9.0
linter, v1.11.3
linter-clang, v3.4.4
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-htmlhint, v1.0.3
linter-javac, v1.8.0
linter-jshint, v2.0.2
linter-jsonlint, v1.1.6
linter-less, v2.4.2
linter-php, v1.2.0
linter-pylint, v1.2.0
linter-ruby, v1.2.2
linter-sass-lint, v1.1.2
linter-shellcheck, v1.1.0
linter-xmllint, v1.3.4
local-history, v3.2.3
markdown-scroll-sync, v2.1.2
minimap, v4.20.0
minimap-bookmarks, v0.3.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
pretty-json, v0.4.1
project-manager, v2.7.6
regex-railroad-diagram, v0.11.0
rspec-snippets, v0.4.0
simple-drag-drop-text, v0.3.0
svg-preview, v0.7.4
symbols-tree-view, v0.11.0
sync-settings, v0.7.0
synced-sidebar, v0.4.3
tabs-to-spaces, v1.0.2
tool-bar, v0.3.0
trailing-spaces, v0.3.2
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by baelter** [comment]
Duplicate of #194

**Comment by jerone** [comment]
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by baelter** [comment]
Thanks for the heads up @jerone
