### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/ankur/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by aoberoi** [Hackafe/atom-sync-settings#216]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/ankur/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/ankur/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/ankur/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/ankur/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/ankur/.atom/packages/sync-settings/lib/sync-settings.coffee:300:16)
    at Object.SyncSettings.checkForUpdate (/Users/ankur/.atom/packages/sync-settings/lib/sync-settings.coffee:61:21)
    at Immediate._onImmediate (/Users/ankur/.atom/packages/sync-settings/lib/sync-settings.coffee:44:19)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
  2x -0:45.8.0 core:close (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:23.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-typescript",
      "color-picker"
    ],
    "projectHome": "/Users/ankur/Developer",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "19c767a6-42c4-4fd8-a10f-19857f4d3342",
    "_lastBackupHash": "cbe8e1c7ecc0c006bb714c802b32e358a4deb0ba",
    "gistId": "348dd99e1b984f8a7a28",
    "personalAccessToken": "6d058f67c37d865aa8bc6be0fb25655e08581b28"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-jade, v0.3.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
emmet, v2.4.2
linter, v1.11.3
linter-eslint, v7.0.0
linter-jshint, v2.0.2
react, v0.14.1
sync-settings, v0.7.0
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by aoberoi** [comment]
duplicate of #194

**Comment by jerone** [comment]
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.
