### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/andypike/.atom/packages/sync-sett...

### ISSUE THREAD

**Issue by andypike** [Hackafe/atom-sync-settings#221]
To reproduce I just upgraded my package within Atom settings from 0.6.0 to 0.7.0 and the error message was displayed.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/andypike/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/andypike/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/andypike/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/andypike/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/andypike/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/andypike/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/andypike/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -3:42.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ],
    "packagesWithKeymapsDisabled": [
      "rspec",
      "goto"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "SNIP",
    "_lastBackupHash": "SNIP",
    "gistId": "35f699430f1828ae4af6",
    "personalAccessToken": "SNIP"
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.18
goto-definition, v1.1.12
json-colorer, v0.3.0
language-elixir, v0.12.3
language-haml, v0.23.15
language-markdown, v0.11.0
language-slim, v0.5.0
linter, v1.11.3
linter-jshint, v2.0.2
linter-rubocop, v0.4.7
pretty-json, v0.4.1
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by andypike** [comment]
Actually this looks like a duplicate of #194 so I'll close this issue.
