### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory[...]/routes.json

### ISSUE THREAD

**Issue by Nephrited** [Hackafe/atom-sync-settings#223]
Happened instantly upon upgrading to 0.7.0

Reproduction steps

1. Install version 0.7.0 of atom-sync-settings
2. Read error message

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.4
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '[...]/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '[...]/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports ([...]/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports ([...]/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient ([...]/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate ([...]/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate ([...]/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -3:07.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:05.1.0 core:copy (atom-text-editor.editor.is-focused)
     -3:04.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:03.3.0 application:new-file (atom-text-editor.editor.mini.is-focused)
     -3:02.3.0 core:paste (atom-text-editor.editor.is-focused)
     -2:59.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:58.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:06.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.seti-ui-no-icons.tinted-tab-bar.compact-tab-bar.use-animations.compact-tree-view.blend-tree-view.theme-atom-material-syntax.theme-atom-material-ui.scrollbars-visible-always.has-custom-icons)
     -0:31 core:close (div.package-detail.panels-item)
     -0:26.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:24.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24.9.0 sync-settings:backup (atom-text-editor.editor)
     -0:17.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.8.0 settings-view:open (atom-text-editor.editor)
  6x -0:06.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "atom-radiant-player"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "ddd2642c-7e3e-490d-8bd7-8d519a43698a",
    "_lastBackupHash": "92d11c1c7a432f14a56fc59c4996aa6684ad128d",
    "gistId": "b4a2863fbf8f50223214",
    "personalAccessToken": "1a44a03f96068939e5d22ffb26d11c31772f413b"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.3
atom-material-ui, v1.2.2
atom-radiant-player, v1.0.3
atom-ternjs, v0.13.2
atom-typescript, v8.3.0
emmet, v2.4.2
file-icons, v1.6.18
linter, v1.11.3
linter-jscs, v3.4.8
linter-jshint, v2.0.2
minimap, v4.20.0
project-manager, v2.7.6
sync-settings, v0.7.0

# Dev
No dev packages
```

**Comment by Nephrited** [comment]
Scrap this, duplicate issue.
