### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/timkirtley/.atom/packages/sync-se...

### ISSUE THREAD

**Issue by timkirtley** [Hackafe/atom-sync-settings#224]
[Enter steps to reproduce below:]

1. Just went to update to 0.7.0

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/timkirtley/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/timkirtley/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/timkirtley/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/timkirtley/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/timkirtley/.atom/packages/sync-settings/lib/sync-settings.coffee:300:16)
    at Object.SyncSettings.checkForUpdate (/Users/timkirtley/.atom/packages/sync-settings/lib/sync-settings.coffee:61:21)
    at Immediate._onImmediate (/Users/timkirtley/.atom/packages/sync-settings/lib/sync-settings.coffee:44:19)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -0:40.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-material-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "d93e2750-9625-4622-baed-81bfbd50ce98",
    "_lastBackupHash": "12fce95f2286a7f53ac5e4cadd6a1a03a66abf24",
    "gistId": "805d76341702113d31c0",
    "personalAccessToken": "bbdcf0e62c6285e04f748fcdfb72616aae2c8fa6"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.3
emmet, v2.4.2
file-icons, v1.6.18
jquery-snippets, v11.0.0
jshint, v1.8.3
less-than-slash, v0.12.3
node_modules, vundefined
pigments, v0.24.4
project-manager, v2.7.6
sync-settings, v0.7.0
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by timkirtley** [comment]
Upon restart Atom v0.7.0 is installed though, so doesnt seem too serious

**Comment by jerone** [comment]
Duplicate of https://github.com/Hackafe/atom-sync-settings/issues/194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by timkirtley** [comment]
Ah yeah, thanks for the heads up.
