### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by atalargo** [Hackafe/atom-sync-settings#23]
[Enter steps to reproduce below:]

1. Install atom-sync-settings from settings/packages
2. launch Settings upload from Menu > Packages > Synchronize settings > Upload

(i remove my token from the trace, but it was set)

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/fruardum/.atom/packages/sync-settings/lib/sync-settings.coffee:57

TypeError: Cannot read property 'name' of undefined
  at Object.module.exports.getPackages (/Users/fruardum/.atom/packages/sync-settings/lib/sync-settings.coffee:57:8)
  at Object.module.exports.upload (/Users/fruardum/.atom/packages/sync-settings/lib/sync-settings.coffee:31:34)
  at atom-text-editor.<anonymous> (/Users/fruardum/.atom/packages/sync-settings/lib/sync-settings.coffee:19:71)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
  2x -2:28.7 core:paste (atom-text-editor#sync-settings.gistId.editor.mini)
     -0:01.5 sync-settings:upload (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "composer",
      "behat-atom"
    ]
  },
  "sync-settings": {
    "gistId": "atom-sync",
    "personalAccessToken": "..."
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
autocomplete-plus, v2.0.6
coffee-lint, v0.7.3
git-log, v0.2.0
git-tab-status, v1.5.3
jsonlint, v1.0.0
language-twig, v1.5.2
linter, v0.11.0
linter-csslint, v0.0.11
linter-flow, v0.1.3
linter-haml, v0.1.0
linter-php, v0.0.11
linter-rubocop, v0.2.1
linter-ruby, v0.1.4
linter-scss-lint, v0.0.11
php-twig, v3.0.0
phpunit, v1.0.9
phpunit-snippets, v0.1.0
project-manager, v1.15.5
rsense, v0.6.0
ruby-block-converter, v3.1.0
save-session, v0.11.3
script, v2.16.0
slash-closer, v0.7.1
symbols-tree-view, v0.4.0
symfony-snippets, v0.3.0
sync-settings, v0.2.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by RossBarnie** [comment]
I know you said you removed your Personal Access Token from the trace, but did you create a new gist and set the Gist ID setting?

**Comment by dsnipe** [comment]
I have same problem. 
After short investigation I found, that problem might be in `for..in` cycle, that generated by coffeescript ([source](https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L56))
So, that part generates code:
```javascript
var info, name, theme, version, _ref, _ref1;
_ref = atom.packages.getLoadedPackages();
for (name in _ref) {
  info = _ref[name];
  _ref1 = info.metadata, name = _ref1.name, version = _ref1.version, theme = _ref1.theme;
  ({
    name: name,
    version: version,
    theme: theme
  });
}
```
That iterates through all properties of array, even inherited. If any other package mixed in an array of something, we get an error.
In my case package – 'Remember Session'.
Simple check `hasOwnProperty` or `forEach` iteration can fix it.

**Comment by jerone** [comment]
Fixed by https://github.com/Hackafe/atom-sync-settings/pull/24
