### ISSUE TITLE
Proxy problemen: Uncaught SyntaxError: Unexpected token c

### ISSUE THREAD

**Issue by chaz2x4** [Hackafe/atom-sync-settings#51]
[Enter steps to reproduce below:]

1. ... Behind corporate proxy
2. ... Try to download settings

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8 Enterprise
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.2.2

### Stack Trace

Uncaught SyntaxError: Unexpected token c

```
At file:///C:/Users/cgeorge/AppData/Local/atom/app-0.199.0/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5Ccgeorge%5C%5C.atom%22%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Ccgeorge%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.199.0%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Ccgeorge%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.199.0%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.199.0%22%2C%22shellLoadTime%22%3A324%2C%22initialPaths%22%3A%5B%22C%3A%5C%5CUsers%5C%5Ccgeorge%5C%5C.atom%22%5D%7D:1

SyntaxError: Unexpected token c
  at Object.parse (native)
  at C:\Users\cgeorge\.atom\packages\sync-settings\lib\sync-settings.coffee:82:24
  at Object.proto.sendError (C:\Users\cgeorge\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\index.js:32:13)
  at C:\Users\cgeorge\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:315:29
  at callCallback (C:\Users\cgeorge\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at ClientRequest.<anonymous> (C:\Users\cgeorge\.atom\packages\sync-settings\node_modules\github\index.js:809:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:24.4.0 sync-settings:download (atom-text-editor.editor.is-focused)
  9x -0:22.3.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -0:05.5.0 settings-view:open (atom-pane.pane.active)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "gistId": "e627f2123fd3cd041ba6",
    "personalAccessToken": "[removedfornow]"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by jerone** [comment]
Apparently something [went wrong](https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L82) contacting your gist. Is the gist id valid (link?)? Is your personal access token valid? What [message appeared](https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L81) in your console?

**Comment by YossyTKB** [comment]
I also encountered this problem too.
Proxy setting may be related.
When my network uses proxy, upload/download failed.
When I changed the network not using proxy, it successed.

**Comment by kornicameister** [comment]
I am also having same issue while behing corporate proxy.

**Comment by chaz2x4** [comment]
Apparently corporate proxy blocks communication with anything. Atom itself
has this problem.

On Mon, May 18, 2015, 17:16 Jeroen van Warmerdam <notifications@github.com>
wrote:

> Apparently something went wrong
> <https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L82>
> contacting your gist. Is the gist id valid (link?)? Is your personal access
> token valid? What message appeared
> <https://github.com/Hackafe/atom-sync-settings/blob/master/lib/sync-settings.coffee#L81>
> in your console?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hackafe/atom-sync-settings/issues/51#issuecomment-103252870>
> .
>
-- 

Chaz George

**Comment by x44x45x41x4E** [comment]
Having the same issue on a Linux Mint 17. Here's the stack strace: 

```
TypeError: Cannot read property 'getUserKeymapPath' of undefined
  at /home/kgallarin/.atom/packages/sync-settings/lib/sync-settings.coffee:96:41
  at /home/kgallarin/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:342:17
  at callCallback (/home/kgallarin/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/home/kgallarin/.atom/packages/sync-settings/node_modules/github/index.js:796:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)
```
Gist ID is correct and token is a new one so I believe it's still valid. Thanks.

**Comment by jerone** [comment]
Fixed in https://github.com/Hackafe/atom-sync-settings/commit/292b1654477341bdd344465dfee135bba3a516ee

**Comment by mattandrews** [comment]
I'm still seeing this on `0.4.0`.

**Comment by jerone** [comment]
[**@mattandrews**](https://github.com/mattandrews) commented on [16 jun. 2015 18:13 CEST](https://github.com/Hackafe/atom-sync-settings/issues/51#issuecomment-112482780 "2015-06-16T16:13:40Z - Replied by Github Comment Enhancer"):
> I'm still seeing this on `0.4.0`.

Can you specify what you are "seeing" ...

**Comment by mattandrews** [comment]
Sorry – the exact same error as @chaz2x4., but on OS X.

**Comment by asolfre** [comment]
Same on 0.5.0

**Comment by jgopel** [comment]
Seeing the same issue on 0.6.0 behind a corporate firewall. Seems like this is the same issue mentioned in #118 as well. I'm getting the error when I try to restore from an existing gist with my settings saved in it. I have not tried a backup to a fresh gist.

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0


### Stack Trace

Uncaught SyntaxError: Unexpected token c

```
At file:///C:/Users/gopel/AppData/Local/atom/app-1.0.7/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5Cgopel%5C%5C.atom%22%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Cgopel%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.7%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Cgopel%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.7%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.7%22%2C%22shellLoadTime%22%3A2389%2C%22initialPaths%22%3A%5B%22C%3A%5C%5CUsers%5C%5Cgopel%5C%5C.atom%22%5D%7D:1

SyntaxError: Unexpected token c
  at Object.parse (native)
  at C:\Users\gopel\.atom\packages\sync-settings\lib\sync-settings.coffee:158:24
  at Object.proto.sendError (C:\Users\gopel\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\index.js:32:13)
  at C:\Users\gopel\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:315:29
  at callCallback (C:\Users\gopel\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at ClientRequest.<anonymous> (C:\Users\gopel\.atom\packages\sync-settings\node_modules\github\index.js:809:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:58.7.0 command-palette:toggle (button.btn.icon.enablement.icon-playback-pause)
     -0:55.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:52.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:52.2.0 sync-settings:restore (button.btn.icon.enablement.icon-playback-pause)
     -0:37.6.0 command-palette:toggle (div.settings-view.pane-item)
     -0:36.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:36.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:33.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.6.0 sync-settings:restore (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "96f66029-64f6-4836-9dda-12dce250b38a",
    "personalAccessToken": "1c7134927577ff1d0765ce6b97974b165709582a",
    "gistId": "3fd906cd590c7a9bcff9"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by jerone** [comment]
Duplicate https://github.com/Hackafe/atom-sync-settings/issues/26

**Comment by dirk-thomas** [comment]
@jgopel In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by jgopel** [comment]
@dirk-thomas Thanks for the heads up
