### ISSUE TITLE
Uncaught SyntaxError: Unexpected token s

### ISSUE THREAD

**Issue by fuchen** [Hackafe/atom-sync-settings#53]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Microsoft Windows 7 旗舰版 
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.2.2

### Stack Trace

Uncaught SyntaxError: Unexpected token s

```
At file:///C:/Users/fcn0590/AppData/Local/atom/app-0.201.0/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5CPython27%5C%5CLib%5C%5Csite-packages%5C%5Cpylint-1.4.3-py2.7.egg%5C%5Cpylint%22%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Cfcn0590%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.201.0%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Cfcn0590%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.201.0%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.201.0%22%2C%22initialPaths%22%3A%5B%22C%3A%5C%5CPython27%5C%5CLib%5C%5Csite-packages%5C%5Cpylint-1.4.3-py2.7.egg%5C%5Cpylint%22%5D%7D:1

SyntaxError: Unexpected token s
  at Object.parse (native)
  at C:\Users\fcn0590\.atom\packages\sync-settings\lib\sync-settings.coffee:64:26
  at Object.proto.sendError (C:\Users\fcn0590\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\index.js:32:13)
  at C:\Users\fcn0590\.atom\packages\sync-settings\node_modules\github\api\v3.0.0\gists.js:180:29
  at callCallback (C:\Users\fcn0590\.atom\packages\sync-settings\node_modules\github\index.js:743:17)
  at ClientRequest.<anonymous> (C:\Users\fcn0590\.atom\packages\sync-settings\node_modules\github\index.js:809:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketOnEnd (_http_client.js:283:9)
  at emitNone (events.js:72:20)
  at TLSSocket.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -1:32 sync-settings:upload (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "github-2014"
    ],
    "ignoredNames": [
      "*.pyc"
    ]
  },
  "sync-settings": {
    "personalAccessToken": "dbc5d05d6cda5b432bdc3f291bda0d05bd41f820",
    "gistId": "AtomSettings"
  }
}
```

### Installed Packages

```coffee
# User
github-2014, v3.5.0
highlight-selected, v0.9.3
language-glsl, v2.0.0
language-lua, v0.9.3
linter, v0.12.6
linter-lua, v0.1.5
linter-pylint, v0.2.2
project-manager, v1.15.7
sync-settings, v0.2.2
terminal-status, v1.6.7

# Dev
No dev packages
```

**Comment by jerone** [comment]
Related to https://github.com/Hackafe/atom-sync-settings/issues/51

**Comment by jerone** [comment]
Probably fixed in https://github.com/Hackafe/atom-sync-settings/commit/292b1654477341bdd344465dfee135bba3a516ee

Please reopen if still happens.

**Comment by dirk-thomas** [comment]
In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.
