### ISSUE TITLE
Uncaught SyntaxError: Unexpected token E

### ISSUE THREAD

**Issue by ronaldho** [Hackafe/atom-sync-settings#65]
Actually not sure what's going on here... can I get some help on how to resolve this? 

I put in my Gist Key and it doesn't seem to be complaining about that

[Enter steps to reproduce below:]

1. Throws the error on upload

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.4.0

### Stack Trace

Uncaught SyntaxError: Unexpected token E

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22includeDeprecatedAPIs%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%220.208.0%22%2C%22shellLoadTime%22%3A723%2C%22initialPaths%22%3A%5B%22atom%3A%2F%2Fconfig%22%5D%7D:1

SyntaxError: Unexpected token E
  at Object.parse (native)
  at ~/.atom/packages/sync-settings/lib/sync-settings.coffee:70:26
  at Object.proto.sendError (~/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:32:13)
  at Object.self.(anonymous function).(anonymous function) [as edit] (~/.atom/packages/sync-settings/node_modules/github/index.js:359:33)
  at Object.module.exports.upload (~/.atom/packages/sync-settings/lib/sync-settings.coffee:63:27)
  at atom-workspace.<anonymous> (~/.atom/packages/sync-settings/lib/sync-settings.coffee:31:69)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  2x -0:19.4.0 sync-settings:upload (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "background-tips"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "sync-settings": {
    "personalAccessToken": "379d0f3584cbe8b077d4c4741aeb56caf9d57da3"
  }
}
```

### Installed Packages

```coffee
# User
sync-settings, v0.4.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by ronaldho** [comment]
Derp! I figured it out. Just didn't configure my gist id correctly

**Comment by jerone** [comment]
"_Experience is making mistakes and learning from them._" - Bill Ackman

**Comment by dirk-thomas** [comment]
Also in the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by ronaldho** [comment]
thanks @dirk-thomas ! I have since revoked it
