### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by takamoja** [Hackafe/atom-sync-settings#94]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.9.5
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.5.0

### Stack Trace

Uncaught TypeError: object is not a function

```
At /Users/moriitakayuki/.atom/packages/sync-settings/lib/sync-settings.coffee:150

TypeError: object is not a function
  at /Users/moriitakayuki/.atom/packages/sync-settings/lib/sync-settings.coffee:150:7
  at /Users/moriitakayuki/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:342:17
  at callCallback (/Users/moriitakayuki/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/Users/moriitakayuki/.atom/packages/sync-settings/node_modules/github/index.js:796:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:01.5.0 sync-settings:restore (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "sync-settings": {
    "personalAccessToken": "d29437de28ea4f0475cc40d798f9eeec1f5e962a",
    "gistId": "d9090d0e06171c640911"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
color-picker, v2.0.7
css-snippets, v0.8.0
docblockr, v0.7.2
emmet, v2.3.12
file-icons, v1.5.8
highlight-line, v0.11.0
highlight-selected, v0.10.1
japanese-menu, v0.7.0
japanese-wrap, v0.2.7
minimap, v4.10.2
minimap-color-highlight, v4.1.4
minimap-highlight-selected, v4.3.0
pigments, v0.8.2
save-session, v0.15.6
seti-syntax, v0.4.0
seti-ui, v0.7.1
sync-settings, v0.5.0
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by varemenos** [comment]
@takamoja you should go to github and regenerate/remove that access token!

**Comment by eduardot42** [comment]
This is also happening to me whenever I try to restore a backup for the first time on a separate machine. The idea of this is to sync across machines, so not being able to do that defeats the purpose of having this package. I reissued the access token, and that does not help. I'll try some other workarounds and see what happens.

**Comment by dirk-thomas** [comment]
@eduardot42 In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.
