### ISSUE TITLE
Uncaught SyntaxError: Unexpected token g

### ISSUE THREAD

**Issue by da1nonly** [Hackafe/atom-sync-settings#95]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.5.0

### Stack Trace

Uncaught SyntaxError: Unexpected token g

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2FAli%2FGithub%2FPersonal%2FSyntro%2Fsyntro%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2FAli%2FGithub%2FPersonal%2FSyntro%2Fsyntro%22%5D%7D:1

SyntaxError: Unexpected token g
  at Object.parse (native)
  at /Users/Ali/.atom/packages/sync-settings/lib/sync-settings.coffee:99:24
  at Object.proto.sendError (/Users/Ali/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:32:13)
  at /Users/Ali/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/gists.js:180:29
  at callCallback (/Users/Ali/.atom/packages/sync-settings/node_modules/github/index.js:743:17)
  at ClientRequest.<anonymous> (/Users/Ali/.atom/packages/sync-settings/node_modules/github/index.js:809:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:933:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:11.5.0 project-manager:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.9.0 sync-settings:backup (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "minimap",
      "pigments",
      "seti-icons",
      "close-on-left"
    ]
  },
  "sync-settings": {
    "personalAccessToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "gistId": "30a3d994410d8546da0a"
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.1
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-ruby, v1.4.0
aligner-scss, v1.0.1
angularjs, v0.3.0
autocomplete-php, v0.3.6
autocomplete-ruby, v0.1.0
color-picker, v2.0.7
file-icons, v1.5.8
hashrocket, v0.4.8
language-gherkin, v1.0.2
linter, v1.1.0
linter-clang, v2.26.1
linter-jshint, v0.1.7
linter-php, v0.0.15
linter-rubocop, v0.2.7
monokai, v0.14.0
project-manager, v1.15.10
remote-edit, v1.8.4
ruby-block, v0.3.4
sync-settings, v0.5.0
tree-view-breadcrumb, v0.6.0

# Dev
No dev packages
```

**Comment by jerone** [comment]
Can you provide some steps to reproduce...

**Comment by da1nonly** [comment]
not sure how to reproduce, but i think it occurred after installing project manager plugin,

**Comment by jerone** [comment]
Is above your complete config file?

Without some clear steps to reproduce I can't help you fix this issue. We are however in the process of completely rewriting this package, so that might fix your problem when it releases.

**Comment by groupsky** [comment]
@da1nonly your token is posted in public as part as Config dump generated from Atom

You **must** [revoke it](https://github.com/settings/tokens), before someone does bad things to your account!

for more info ref #98

**Comment by dirk-thomas** [comment]
Without further information this can not be debugged. Assuming this is not a problem anymore I will close this ticket. If you are still experiencing the problem please comment with more information.
